---
version: '3'

services:
    master:
        image: ros:noetic-ros-core-focal
        container_name: master
        tty: true
        ipc: host
        privileged: true
        restart: unless-stopped
    dev:
        build: .
        container_name: dev
        tty: true
        ipc: host
        privileged: true
        environment:
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '../yolor:/yolor'
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
