---
version: '3'

services:
    dev-env:
        build: .
        container_name: dev-env
        tty: true
        ipc: host
        privileged: true
        environment:
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '../src:/app'
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
