---
version: '3'

services:
    yolor:
        build: .
        container_name: object-detection
        tty: true
        ipc: host
        privileged: true
        environment:
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '../yolor:/yolor'
            - '../dataset/coco:/coco'
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
